CHEER_LIST=['hi','hello','How are you']
BYE_LIST=['yes! thanks','yes! thank you','thank you','goodbye','bye', 'thanks']
ADMIN=['Zhipeng Chang']

GROUP = "google"

QUESTION_DIC = {
"Chatbot type": [1, "select detailed_decription, description from ARADMIN.HPD_HELP_DESK WHERE manufacturer = 'Google Inc'"], 
'Opportunities for COE': [2, "This answer will be updated by one of our supporting staffs soon ..."],
'Use cases in industry': [3, "This answer will be updated by one of our supporting staffs soon ..."],
'Use cases in municipal government': [4, "This answer will be updated by one of our supporting staffs soon ..."],
'Recommendations for COE': [5, "This answer will be updated by one of our supporting staffs soon ..."],
'Benefits for COE': [6, "This answer will be updated by one of our supporting staffs soon ..."],
'Use cases for COE': [7, "This answer will be updated by one of our supporting staffs soon ..."],
'Next steps': [8, "This answer will be updated by one of our supporting staffs soon ..."],

"How to add a sheet into a google spreadsheet": [9, "This answer will be updated by one of our supporting staffs soon ..."],
"How to delegate meetings": [10, "This answer will be updated by one of our supporting staffs soon ..."],
"How to register to vote": [11, "This answer will be updated by one of our supporting staffs soon ..."],
"How to see who is part of a google distribution list": [12, "This answer will be updated by one of our supporting staffs soon ..."],
"How to send a Word Doc": [13, "This answer will be updated by one of our supporting staffs soon ..."],
"How to change settings to a shared folder": [14, "This answer will be updated by one of our supporting staffs soon ..."],
"How to change ownership of a folder in google drive": [15, "This answer will be updated by one of our supporting staffs soon ..."],
"How to do a bulk move of email": [16, "This answer will be updated by one of our supporting staffs soon ..."],
"How to figure out who is in a group": [17, "This answer will be updated by one of our supporting staffs soon ..."],
"How to use draw.io": [18, "This answer will be updated by one of our supporting staffs soon ..."],
"How many ounces in a gallon": [19, "This answer will be updated by one of our supporting staffs soon ..."],
"How many weeks in a year": [20, "This answer will be updated by one of our supporting staffs soon ..."],
"How to use draw.io": [21, "This answer will be updated by one of our supporting staffs soon ..."],
"How to add shared calendar": [22, "This answer will be updated by one of our supporting staffs soon ..."],
"How to bulk delete email": [23, "This answer will be updated by one of our supporting staffs soon ..."],
"How to save full emails including attachments to shared drive": [24, "This answer will be updated by one of our supporting staffs soon ..."],
"How to copy a google document with complete markup  of comments and changes": [25, "This answer will be updated by one of our supporting staffs soon ..."],
"How to set a document on the web page to ask if you want to make a copy": [26, "This answer will be updated by one of our supporting staffs soon ..."],
"How to remove his name when sending emails on behalf of": [27, "This answer will be updated by one of our supporting staffs soon ..."],
"How to make reservations for Recurring general meetings": [28, "This answer will be updated by one of our supporting staffs soon ..."],
"How to connect with the chromebox": [29, "This answer will be updated by one of our supporting staffs soon ..."],
"How to clear cache from Internet Explorer": [30, "This answer will be updated by one of our supporting staffs soon ..."],
"How to inert a textbox in google docs": [31, "This answer will be updated by one of our supporting staffs soon ..."],
"How to disable Auto Correct in Google mail": [32, "This answer will be updated by one of our supporting staffs soon ..."],
"How to get an original template back in Google Docs after it has been modified": [33, "This answer will be updated by one of our supporting staffs soon ..."],
"How to log into Google Mail": [34, "This answer will be updated by one of our supporting staffs soon ..."],
"How to locate completed form": [35, "This answer will be updated by one of our supporting staffs soon ...", "link"],
"How to manage Google Group": [36, "This answer will be updated by one of our supporting staffs soon ..."],
"How to save emails on Flash drive": [37, "This answer will be updated by one of our supporting staffs soon ..."],
"How to look up an owner of a Calendar": [38, "This answer will be updated by one of our supporting staffs soon ..."],
"How to create appointment slots": [39, "This answer will be updated by one of our supporting staffs soon ..."],
"How to add members to business shared account (BSA)": [40, "This answer will be updated by one of our supporting staffs soon ..."],
"How to redirect a google page to another site": [41, "This answer will be updated by one of our supporting staffs soon ..."],
"What is the biggest size email you can send": [42, "This answer will be updated by one of our supporting staffs soon ..."],
"How to convert pdf to excel": [43, "This answer will be updated by one of our supporting staffs soon ..."],
"How to open PDF in Chrome": [44, "This answer will be updated by one of our supporting staffs soon ..."],
"How to open Chrome ": [45, "This answer will be updated by one of our supporting staffs soon ..."],
"How to set Chrome as default browser": [46, "This answer will be updated by one of our supporting staffs soon ..."],


"What time is it in london": [47, "This answer will be updated by one of our supporting staffs soon ..."],
"How old am i": [48, "This answer will be updated by one of our supporting staffs soon ..."],
"How to get rid of bed bugs": [49, "This answer will be updated by one of our supporting staffs soon ..."],
"How to draw a rose": [50, "This answer will be updated by one of our supporting staffs soon ..."],
"How to make pizza": [51, "This answer will be updated by one of our supporting staffs soon ..."],
"How many grams in a pound": [52, "This answer will be updated by one of our supporting staffs soon ..."],
"How many ounces in a quart": [53, "This answer will be updated by one of our supporting staffs soon ..."],
"How do you spell": [54, "This answer will be updated by one of our supporting staffs soon ..."],
"How to use snapchat": [55, "This answer will be updated by one of our supporting staffs soon ..."],
"What is your name": [56, "This answer will be updated by one of our supporting staffs soon ..."],
"How to make french toast": [57, "This answer will be updated by one of our supporting staffs soon ..."],
"How to make slime": [58, "This answer will be updated by one of our supporting staffs soon ..."],
"How many tablespoons in a cup": [59, "This answer will be updated by one of our supporting staffs soon ..."],
"What time is the superbowl": [60, "This answer will be updated by one of our supporting staffs soon ..."],
"How many oz in a cup": [61, "This answer will be updated by one of our supporting staffs soon ..."],
"What time is sunset": [62, "This answer will be updated by one of our supporting staffs soon ..."],
"How to write a check": [63, "This answer will be updated by one of our supporting staffs soon ..."],
"How to tie a bowtie": [64, "This answer will be updated by one of our supporting staffs soon ..."],
"when is daylight saving time": [65, "This answer will be updated by one of our supporting staffs soon ..."],
"How many days in a year": [66, "This answer will be updated by one of our supporting staffs soon ..."],
"What does hmu mean": [67, "This answer will be updated by one of our supporting staffs soon ..."],
"How many days until christmas": [68, "This answer will be updated by one of our supporting staffs soon ..."],
"How to make money online": [69, "This answer will be updated by one of our supporting staffs soon ..."],
"What time is it in australia": [70, "This answer will be updated by one of our supporting staffs soon ..."],
"when is memorial day": [71, "This answer will be updated by one of our supporting staffs soon ..."],
"when is labor day": [72, "This answer will be updated by one of our supporting staffs soon ..."],
"What is the temp": [73, "This answer will be updated by one of our supporting staffs soon ..."],
"What is the temperature": [74, "This answer will be updated by one of our supporting staffs soon ..."],
"What time is it in hawaii": [75, "This answer will be updated by one of our supporting staffs soon ..."],
"How to solve a rubix cube": [76, "This answer will be updated by one of our supporting staffs soon ..."],
"How many countries in the world": [77, "This answer will be updated by one of our supporting staffs soon ..."],
"who sings this song": [78, "This answer will be updated by one of our supporting staffs soon ..."],
"How many teaspoons in a tablespoon": [79, "This answer will be updated by one of our supporting staffs soon ..."],
"How long to boil eggs": [80, "This answer will be updated by one of our supporting staffs soon ..."],
"How many centimeters in an inch": [81, "This answer will be updated by one of our supporting staffs soon ..."],
"why is the sky blue": [82, "This answer will be updated by one of our supporting staffs soon ..."],
"How to write a cover letter": [83, "This answer will be updated by one of our supporting staffs soon ...", "www.google.ca"],
"What is the meaning of life": [84, "drink tea hahahah", "www.google.ca"],
}
