CHEER_LIST=['hi','hello','how are you?','how are you','Hi JacksonBot']
BYE_LIST=['thank you','goodbye','bye']


GROUP = "google"
QUESTION_DIC = {
"Chatbot type": [1, "answer"], 
'Opportunities for COE': [2, "answer"],
'Use cases in industry': [3, "answer"],
'Use cases in municipal government': [4, "answer"],
'Recommendations for COE': [5, "answer"],
'Benefits for COE': [6, "answer"],
'Use cases for COE': [7, "answer"],
'Next steps': [8, "answer"],
"what is my ip": [9, "answer"],
"what time is it": [10, "answer"],
"how to register to vote": [11, "answer"],
"how to tie a tie": [12, "answer"],
"can you run it": [13, "answer"],
"what song is this": [14, "answer"],
"how to lose weight": [15, "answer"],
"how many ounces in a cup": [16, "answer"],
"when is mothers day": [17, "answer"],
"how many ounces in a pound": [18, "answer"],
"how many ounces in a gallon": [19, "answer"],
"how many weeks in a year": [20, "answer"],
"when is fathers day": [21, "answer"],
"what is my ip address": [22, "answer"],
"can i run it": [23, "answer"],
"how to download youtube videos": [24, "answer"],
"how to screenshot on mac": [25, "answer"],
"how old is donald trump": [26, "answer"],
"how to lose weight fast": [27, "answer"],
"where are you now": [28, "answer"],
"how to make pancakes": [29, "answer"],
"when we were young": [30, "answer"],
"how to make money": [31, "answer"],
"how many grams in an ounce": [32, "answer"],
"how many feet in a mile": [33, "answer"],
"what time is it in california": [34, "answer"],
"what does smh mean": [35, "answer", "link"],
"how old is hillary clinton": [36, "answer"],
"how to lose belly fat": [37, "answer"],
"is it going to rain today": [38, "answer"],
"where is my phone": [39, "answer"],
"what is the weather today": [40, "answer"],
"how to download videos from youtube": [41, "answer"],
"how to boil eggs": [42, "answer"],
"how to delete instagram account": [43, "answer"],
"how to take a screenshot on a mac": [44, "answer"],
"how many cups in a gallon": [45, "answer"],
"how many days till christmas": [46, "answer"],
"what time is it in london": [47, "answer"],
"how old am i": [48, "answer"],
"how to get rid of bed bugs": [49, "answer"],
"how to draw a rose": [50, "answer"],
"how to make pizza": [51, "answer"],
"how many grams in a pound": [52, "answer"],
"how many ounces in a quart": [53, "answer"],
"how do you spell": [54, "answer"],
"how to use snapchat": [55, "answer"],
"what is your name": [56, "answer"],
"how to make french toast": [57, "answer"],
"how to make slime": [58, "answer"],
"how many tablespoons in a cup": [59, "answer"],
"what time is the superbowl": [60, "answer"],
"how many oz in a cup": [61, "answer"],
"what time is sunset": [62, "answer"],
"how to write a check": [63, "answer"],
"how to tie a bowtie": [64, "answer"],
"when is daylight saving time": [65, "answer"],
"how many days in a year": [66, "answer"],
"what does hmu mean": [67, "answer"],
"how many days until christmas": [68, "answer"],
"how to make money online": [69, "answer"],
"what time is it in australia": [70, "answer"],
"when is memorial day": [71, "answer"],
"when is labor day": [72, "answer"],
"what is the temp": [73, "answer"],
"what is the temperature": [74, "answer"],
"what time is it in hawaii": [75, "answer"],
"how to solve a rubix cube": [76, "answer"],
"how many countries in the world": [77, "answer"],
"who sings this song": [78, "answer"],
"how many teaspoons in a tablespoon": [79, "answer"],
"how long to boil eggs": [80, "answer"],
"how many centimeters in an inch": [81, "answer"],
"why is the sky blue": [82, "answer"],
"how to write a cover letter": [83, "answer", "www.google.ca"],
"what is the meaning of life": [84, "drink tea hahahah", "www.google.ca"],
}
